apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-exchange
  namespace: default
  labels:
    app: crypto-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-exchange
  template:
    metadata:
      labels:
        app: crypto-exchange
    spec:
      containers:
      - name: crypto-exchange
        image: crypto_exchange_app:1.0.0
        ports:
        - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: crypto-exchange-service
  namespace: default
  labels:
    app: crypto-exchange
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: crypto-exchange
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
  labels:
    app: postgres
spec:
   replicas: 1
   selector:
      matchLabels:
       name: postgres
       app: postgres
   template:
     metadata:
       name: postgres
       labels:
         name: postgres
         app: postgres
     spec:
       containers:
       - name: postgres
         image: postgres:12
         env:
         - name: POSTGRES_USER
           value: postgres
         - name: POSTGRES_PASSWORD
           value: postgres
         ports:
         - containerPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service # Create service
metadata:
  name: postgres-service # Sets the service name
  labels:
    app: postgres # Defines app to create service for
spec:
  type: NodePort # Sets the service type
  ports:
    - port: 5432 # Sets the port to run the postgres application
  selector:
    app: postgres