version: "3.9"

services:
  crypto_exchange:
    container_name: crypto_exchange
    image: crypto_exchange_app:1.0.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-service:5432/postgres
    depends_on:
      - postgres-service
    volumes:
      - ./app:/app
  postgres-service:
    container_name: postgres-service
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}